# Numpy Vectors

In [1]:
#import paskages
import numpy as np

In [3]:
# Generating an array 'a' containing 5 random numbers drawn from a standard normal distribution
a = np.random.randn(5)
a

array([-1.17582742, -0.16044875,  0.45482325, -0.22023935,  0.33488099])

In [4]:
#shape arrat
a.shape

(5,)

In [6]:
# transpose 
print(a.T)


[-1.17582742 -0.16044875  0.45482325 -0.22023935  0.33488099]


In [7]:
# Calculating  dot product of the array 'a' with its transpose and printing the result
print(np.dot(a, a.T))

1.7758287572688356


In [8]:
# Generating a 5x1 array 'a' containing random numbers drawn from a standard normal distribution
a = np.random.randn(5, 1)

a

array([[ 0.10189215],
       [ 1.56542676],
       [-0.30068994],
       [-0.6428945 ],
       [-0.7427984 ]])

In [11]:
#shape array
a.shape

(5, 1)

In [9]:
# transpose  array
a.T


array([[ 0.10189215,  1.56542676, -0.30068994, -0.6428945 , -0.7427984 ]])

In [10]:
print(np.dot(a,a.T))

[[ 0.01038201  0.15950469 -0.03063794 -0.0655059  -0.07568532]
 [ 0.15950469  2.45056094 -0.47070808 -1.00640425 -1.16279649]
 [-0.03063794 -0.47070808  0.09041444  0.19331191  0.22335201]
 [-0.0655059  -1.00640425  0.19331191  0.41331334  0.477541  ]
 [-0.07568532 -1.16279649  0.22335201  0.477541    0.55174946]]
