# trace Quiz Shallow Neural Networks

In [1]:
#import paskages
import numpy as np

In [2]:
## Generate a 4x5 array of random numbers
x=np.random.rand(4,5)
x

array([[0.28729366, 0.25137417, 0.65669843, 0.15144187, 0.30441368],
       [0.89096779, 0.64632956, 0.78600186, 0.75448934, 0.9257346 ],
       [0.73484893, 0.02831539, 0.29290092, 0.39548833, 0.35564799],
       [0.84755986, 0.14412644, 0.14291699, 0.93581121, 0.15998838]])

In [3]:

#sum
y=np.sum(x, axis=1)

# Print the resulting array and its shape
print("Array y:")
print(y)
print("Shape of y:", y.shape)

Array y:
[1.65122181 4.00352314 1.80720155 2.23040288]
Shape of y: (4,)


In [6]:
#another example 
X= np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
print(X.shape)
X

(4, 5)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [10]:
#sum
Y=np.sum(X, axis=1)
print(Y.shape)
Y

(4,)


array([15, 40, 65, 90])